triggers:
  - type meya.keyword
    properties:
        ignorecase: true
        keyword: cms
states:
    first:
        component: cms
        properties:
            space: main
            key: hi
