triggers:
  - type: meya.keyword
    properties:
        ignorecase: true
        keyword: hi
states:
    language:
        component: meya.input_string
        properties:
            text: "What's your preferred language?"
            output: language
            scope: user
    thanks:
        component: meya.text
        properties:
            text: "{{ cms.onboard.thanks }}"