triggers:
  - type: meya.api_ai
    properties:
        client_access_token: c1993f44ab724adf9cb602c7086d16d0
        language: en
states:
    first:
        component: meya.text
        properties:
            text: "{{ flow.service }} with {{ flow.person }} on {{ flow.date }}"