triggers:
  - type: meya.keyword
    properties:
        ignorecase: true
        keyword: settings
states:
    colour:
        component: meya.text
        properties:
            text: "Colour: {{ bot._settings.colour }}"
    timezone:
        component: meya.text
        properties:
            text: "Timezone: {{ bot._settings.timezone }}"
